blank_issues_enabled: false
contact_links:
 - name: Questions
   url: https://forum.authing.cn/
   about: For general questions, support requests and discussions
 - name: Documention
   url: https://docs.authing.cn/v2/reference/sdk-for-sso.html
   about: Authing SDK for SSO
